version: "3.4"
services:
  # moove-node:
  #   build: .
  #   container_name: moove-node
  #   restart: always
  #   ports:
  #     - "3000:3030"
  #   depends_on:
  #     - moove-mongo
  #     - moove-redis
  #     - moove-zookeeper
  #     - moove-kafka
  #   environment:
  #     - CONTAINER_SERVICE=Docker
  #     - NODE_ENV=production
  #   networks:
  #     - moove-net

  moove-mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"
    container_name: moove-mongo
    restart: always
    networks:
      - moove-net

  moove-redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: moove-redis
    restart: always
    networks:
      - moove-net

  moove-zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    container_name: moove-zookeeper
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - moove-net

  moove-kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    container_name: moove-kafka
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=moove-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    depends_on:
      - moove-zookeeper
    networks:
      - moove-net

volumes:
  mongo_data:
  zookeeper_data:
  kafka_data:

networks:
  moove-net:
    driver: bridge
