apiVersion: apps/v1
kind: Deployment
metadata:
  name: moove-account-db-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moove-account-db
  template:
    metadata:
      labels:
        app: moove-account-db
    spec:
      containers:
        - name: moove-account-db-cont
          image: postgres
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-user
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              value: accountdb

            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust

---
apiVersion: v1
kind: Service
metadata:
  name: moove-account-db-srv
spec:
  type: ClusterIP
  selector:
    app: moove-account-db
  ports:
    - name: moove-account-db-port
      protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moove-account-db-pvc
spec:
  resources:
    requests:
      storage: "5000Mi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
