apiVersion: apps/v1
kind: Deployment
metadata:
  name: moove-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moove-auth
  template:
    metadata:
      labels:
        app: moove-auth
    spec:
      containers:
        - name: moove-auth-cont
          image: faridmansimli/moove-auth
          ports:
            - containerPort: 3001
          resources:
            limits:
              cpu: "1500m"
              memory: "500Mi"
          env:
            - name: NODE_ENV
              value: development

            - name: APP_NAME
              value: moove-auth

            - name: APP_HOST
              value: moove-auth-srv

            - name: PORT
              value: "3001"

            - name: MONGO_HOST
              value: moove-auth-db-srv

            - name: MONGO_PORT
              value: "27017"

            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-user
                  key: MONGO_USER

            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-password
                  key: MONGO_PASSWORD

            - name: MONGO_DATABASE
              value: authdb

---
apiVersion: v1
kind: Service
metadata:
  name: moove-auth-srv
spec:
  type: ClusterIP
  selector:
    app: moove-auth
  ports:
    - name: moove-auth-port
      protocol: TCP
      port: 3001
      targetPort: 3001
