apiVersion: apps/v1
kind: Deployment
metadata:
  name: moove-places-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moove-places
  template:
    metadata:
      labels:
        app: moove-places
    spec:
      containers:
        - name: moove-places-cont
          image: faridmansimli/moove-places
          ports:
            - containerPort: 3003
          resources:
            limits:
              cpu: "1500m"
              memory: "500Mi"
          env:
            - name: NODE_ENV
              value: development

            - name: APP_NAME
              value: moove-places

            - name: APP_HOST
              value: moove-places-srv

            - name: PORT
              value: "3003"

            - name: MONGO_HOST
              value: moove-places-db-srv

            - name: MONGO_PORT
              value: "27017"

            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-user
                  key: MONGO_USER

            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-password
                  key: MONGO_PASSWORD

            - name: MONGO_DATABASE
              value: placesdb

            - name: KAFKA_URL
              value: kafka-service:9092

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: moove-places-srv
spec:
  type: ClusterIP
  selector:
    app: moove-places
  ports:
    - name: moove-places-port
      protocol: TCP
      port: 3003
      targetPort: 3003
